# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec52958f80c1f054e882404e16d09078203d62779b18aecd28617fe54080bd195d8e3f6bdf1f72ab2391394a4a77d473d1ad1cfbd8e170641e465b1a939b5df6

test:
  secret_key_base: 9629d3a652c5d4dc0521954a6d798f43be5c82950492329a0772cb7d0d5c3f6d4d2467f0b2955ee26844ea8793d3e110fc12366dbf4a51c49478e0fb754808b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
